jobs:
- name: whereisthat
  plan:
  - get: whereisthat-git
    trigger: true
  - config:
      caches:
      - path: $HOME/.m2/repository
      - path: $HOME/.gradle/caches/
      - path: $HOME/.gradle/wrapper/
      container_limits: {}
      image_resource:
        name: ""
        source:
          repository: maven
          tag: 3.8.6-amazoncorretto-11
        type: registry-image
      inputs:
      - name: whereisthat-git
      platform: linux
      run:
        args:
        - -c
        - |
          java -Xmx32m -version
          javac -J-Xmx32m -version

          cd whereisthat-git

          mvn clean
          mvn install
        path: /bin/sh
        user: root
    task: run-tests
  public: true

resources:
- icon: github
  name: whereisthat-git
  source:
    uri: https://github.com/alasdair333/WhereIsThat.git
  type: git